Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
#  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder '.', '/vagrant', disabled: true
#  config.vm.provision "shell", path: "startup.sh"

  config.vm.define "control" do |ansible|
    ansible.vm.hostname = "control-node"
    ansible.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "data" do |ansible|
    ansible.vm.hostname = "data-node"
    ansible.vm.network "private_network", ip: "192.168.56.11"
  end
end
