Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.ssh.insert_key = false
    config.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/home/vagrant/.ssh/id_rsa"
    config.vm.provision "shell", privileged: false, path: "ssh_setup.sh"
  #  config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder '.', '/vagrant', disabled: true
  #  config.vm.provision "shell", path: "startup.sh"
  
    config.vm.define :control do |control|
      control.vm.hostname = "control"
      control.vm.network "private_network", ip: "192.168.56.10", virtualbox_intnet: "internal_net"
      control.vm.provision "shell", privileged: false, path: "ansible_setup.sh"
    end
  
    config.vm.define :db1 do |db1|
      db1.vm.network "private_network", ip: "192.168.56.30", virtualbox_intnet: "internal_net"
    end
  
    config.vm.define :db2 do |db2|
      db2.vm.box = "centos/7"
      db2.vm.network "private_network", ip: "192.168.56.31", virtualbox_intnet: "internal_net"
    end
  
    config.vm.define :db3 do |db3|
      db3.vm.box = "centos/7"
      db3.vm.network "private_network", ip: "192.168.56.32", virtualbox_intnet: "internal_net"
    end

    config.vm.define :app1 do |app1|
        app1.vm.box = "centos/7"
        app1.vm.network "private_network", ip: "192.168.56.21", virtualbox_intnet: "internal_net"
      end
    
    config.vm.define :app2 do |app2|
    app2.vm.box = "centos/7"
    app2.vm.network "private_network", ip: "192.168.56.22", virtualbox_intnet: "internal_net"
    end

    config.vm.define :app3 do |app3|
    app3.vm.box = "centos/7"
    app3.vm.network "private_network", ip: "192.168.56.23", virtualbox_intnet: "internal_net"
    end

    config.vm.define :lb1 do |lb1|
    lb1.vm.box = "centos/7"
    lb1.vm.network "private_network", ip: "192.168.56.40", virtualbox_intnet: "internal_net"
    end

    config.vm.define :lb2 do |lb2|
    lb2.vm.box = "centos/7"
    lb2.vm.network "private_network", ip: "192.168.56.41", virtualbox_intnet: "internal_net"
    end
end
